import { createWriteStream } from 'node:fs';
import { stat, writeFile } from 'node:fs/promises';
import { Transform, type TransformCallback } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import * as tar from 'tar';
import { badRequest, parseCommand } from '@forge/shared';
import type { ProjectRow } from '@forge/db';
import type { BuildSandbox } from '../build/sandbox.js';

/**
 * The build context: one tar of the built tree plus a generated Dockerfile.
 *
 * It is created once and consumed twice — streamed into `docker build`, and
 * (optionally) gzipped into the object store as the deployment's artifact. That
 * matters beyond saving a pass over the bytes: the artifact is then *exactly*
 * what was built, not a second tar taken from a tree that has moved on.
 */

/**
 * Our Dockerfile's name inside the context.
 *
 * Dot-prefixed and namespaced so it does not collide with a `Dockerfile` the
 * project ships. A project that happens to have this exact filename has it
 * overwritten — the sandbox is a copy, so nothing of theirs is lost, and the
 * alternative (honouring a project-supplied Dockerfile) is a feature with its
 * own security surface, not a naming decision.
 */
export const FORGE_DOCKERFILE = '.forge.Dockerfile';

/** Paths never worth shipping into an image, matched against the tar entry name. */
const EXCLUDED = ['./.git/', './.git', './node_modules/.cache/'];

/**
 * Generates the Dockerfile for one project and writes it into the workdir.
 *
 * Three decisions are baked in here, all of them CLAUDE.md §8:
 *
 *  - **Non-root.** `USER 1000:1000` numerically rather than `USER node`, so it
 *    holds on any base image, whether or not it has a `node` user.
 *  - **No secrets in layers.** The project's env vars are *not* `ENV`'d here.
 *    An image layer is a durable, exportable artifact; a secret baked into one
 *    outlives the deployment and leaks with the image. Runtime variables are
 *    passed to `container create` instead, where they live only as long as the
 *    container.
 *  - **Writable only where we say.** The root filesystem is mounted read-only
 *    at run time, so `HOME`, `TMPDIR` and npm's cache are pointed at `/tmp`,
 *    which is the tmpfs. Without this `npm start` fails trying to create a
 *    cache directory it will never use.
 */
export async function writeDockerfile(
  sandbox: BuildSandbox,
  workdir: string,
  project: ProjectRow,
  baseImage: string,
  labels: Record<string, string>,
): Promise<string> {
  // The start command is tokenised by the same non-shell parser the build
  // steps use, and emitted as JSON — CMD's exec form, so there is no shell in
  // the container either.
  const { file, args } = parseCommand(project.start_command);
  const cmd = JSON.stringify([file, ...args]);

  const dockerfile = [
    '# Generated by ForgeCloud. Rewritten on every deployment — do not edit.',
    `FROM ${baseImage}`,
    // As `LABEL` instructions rather than the Engine's `labels` build
    // parameter: that parameter is a JSON-encoded query string and getting it
    // wrong fails silently, whereas these are part of the build and can be read
    // back with `docker inspect`. They are what makes an image identifiable as
    // ours without matching on its name.
    ...Object.entries(labels).map(
      ([key, value]) => `LABEL ${JSON.stringify(key)}=${JSON.stringify(value)}`,
    ),
    'WORKDIR /app',
    // --chown so the unprivileged user can read its own application tree.
    'COPY --chown=1000:1000 . /app',
    'USER 1000:1000',
    'ENV NODE_ENV=production \\',
    '    HOME=/tmp \\',
    '    TMPDIR=/tmp \\',
    '    npm_config_cache=/tmp/.npm \\',
    '    npm_config_update_notifier=false \\',
    '    NO_COLOR=1',
    `EXPOSE ${String(project.app_port)}`,
    `CMD ${cmd}`,
    '',
  ].join('\n');

  const target = sandbox.resolveInside(FORGE_DOCKERFILE, workdir);
  await writeFile(target, dockerfile, 'utf8');
  return dockerfile;
}

/** A `Transform` that refuses to pass more than `limit` bytes. */
class ByteCap extends Transform {
  #bytes = 0;
  constructor(
    private readonly limit: number,
    private readonly what: string,
  ) {
    super();
  }
  get bytes(): number {
    return this.#bytes;
  }
  override _transform(chunk: Buffer, _encoding: BufferEncoding, callback: TransformCallback): void {
    this.#bytes += chunk.length;
    if (this.#bytes > this.limit) {
      callback(
        badRequest(
          'CONTEXT_TOO_LARGE',
          `The ${this.what} exceeded the ${String(this.limit)}-byte limit`,
        ),
      );
      return;
    }
    callback(null, chunk);
  }
}

export type BuildContext = {
  /** Absolute path of the tar, inside the sandbox. */
  path: string;
  sizeBytes: number;
};

/**
 * Tars the workdir into the sandbox.
 *
 * Written to disk rather than piped straight into the daemon because it has two
 * consumers, and because a file gives the size up front — which is what lets a
 * runaway context be refused before the daemon starts reading it. The cap is
 * enforced *while* writing (like the archive extractor's), so a 4 GB
 * `node_modules` fails on the chunk that crosses the line rather than after the
 * whole thing has landed.
 *
 * Symlinks are stored as symlinks (tar's default): they are part of what
 * `npm install` produces, and resolving them would both inflate the context and
 * follow a link the project chose.
 */
export async function createBuildContext(
  sandbox: BuildSandbox,
  workdir: string,
  maxBytes: number,
): Promise<BuildContext> {
  const path = sandbox.resolveInside('context.tar');
  const cap = new ByteCap(maxBytes, 'build context');

  await pipeline(
    tar.create(
      {
        cwd: workdir,
        // Reproducible headers, so an unchanged tree produces an unchanged tar
        // and Docker's layer cache can actually hit.
        portable: true,
        follow: false,
        filter: (entry) => !EXCLUDED.some((prefix) => entry.startsWith(prefix)),
      },
      ['.'],
    ),
    cap,
    createWriteStream(path, { flags: 'wx' }),
  );

  const info = await stat(path);
  return { path, sizeBytes: info.size };
}
