/**
 * Stage: codegen.
 *
 * Writes one TypeScript module per report into `src/generated/reports/`, plus a
 * registry that imports them all. This is the realistic pattern a build like
 * this exists to demonstrate — the same thing GraphQL clients, ORMs and API SDK
 * generators do — and it is what gives the `typecheck` stage a meaningful
 * amount of code to check.
 *
 * The generated modules are checked against the hand-written types in
 * `src/lib/types.ts`, so a template that asks a dimension for a metric it does
 * not carry fails the build here rather than producing `undefined` on a chart.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { line, progress, num } from '../lib/log.mjs';

const GENERATED = 'src/generated';
const REPORTS_DIR = join(GENERATED, 'reports');

/** Per-dimension facts the template needs: source array, row type, label column. */
const DIMENSIONS = {
  day: { source: 'byDay', rowType: 'DayRow', label: 'date', keyExpr: 'item.date', tiebreak: 'a.date < b.date ? -1 : 1' },
  route: { source: 'byRoute', rowType: 'RouteRow', label: 'path', keyExpr: 'item.path', tiebreak: 'a.path < b.path ? -1 : 1' },
  country: { source: 'byCountry', rowType: 'CountryRow', label: 'code', keyExpr: 'item.code', tiebreak: 'a.code < b.code ? -1 : 1' },
  device: { source: 'byDevice', rowType: 'DeviceRow', label: 'name', keyExpr: 'item.name', tiebreak: 'a.name < b.name ? -1 : 1' },
  status: { source: 'byStatus', rowType: 'StatusRow', label: 'code', keyExpr: 'String(item.code)', tiebreak: 'a.code - b.code' },
};

/** Every (dimension, metric) pair the types actually permit. */
const COMBOS = [
  ['day', 'requests'], ['day', 'errors'], ['day', 'bytes'], ['day', 'avgDurationMs'],
  ['route', 'requests'], ['route', 'errors'], ['route', 'errorRate'], ['route', 'bytes'],
  ['route', 'p50Ms'], ['route', 'p95Ms'], ['route', 'p99Ms'],
  ['country', 'requests'], ['country', 'bytes'],
  ['device', 'requests'],
  ['status', 'requests'],
];

const LIMITS = [5, 8, 10, 12, 15, 20];
const DIRECTIONS = ['desc', 'asc'];

const METRIC_LABELS = {
  requests: 'requests',
  errors: 'errors',
  errorRate: 'error rate',
  bytes: 'bytes served',
  avgDurationMs: 'average latency',
  p50Ms: 'median latency',
  p95Ms: 'p95 latency',
  p99Ms: 'p99 latency',
};

const DIMENSION_LABELS = {
  day: 'days',
  route: 'routes',
  country: 'countries',
  device: 'device types',
  status: 'status codes',
};

function unitFor(metric) {
  if (metric === 'bytes') return 'bytes';
  if (metric === 'errorRate') return 'ratio';
  if (metric.endsWith('Ms')) return 'ms';
  return 'count';
}

/** The plan for `count` modules: cycle the combos, varying limit and direction. */
export function planModules(count) {
  const plan = [];
  for (let i = 0; i < count; i++) {
    const [dimension, metric] = COMBOS[i % COMBOS.length];
    const limit = LIMITS[Math.floor(i / COMBOS.length) % LIMITS.length];
    const direction = DIRECTIONS[Math.floor(i / (COMBOS.length * LIMITS.length)) % DIRECTIONS.length];
    const generation = Math.floor(i / (COMBOS.length * LIMITS.length * DIRECTIONS.length));
    const id = `${dimension}-${metric}-${direction}-${limit}${generation > 0 ? `-v${generation + 1}` : ''}`;
    plan.push({
      id,
      file: `${id}.ts`,
      dimension,
      metric,
      limit,
      direction,
      unit: unitFor(metric),
      title:
        `${direction === 'desc' ? 'Top' : 'Bottom'} ${limit} ${DIMENSION_LABELS[dimension]} ` +
        `by ${METRIC_LABELS[metric]}`,
    });
  }
  return plan;
}

function moduleSource(spec) {
  const dim = DIMENSIONS[spec.dimension];
  const comparator =
    spec.direction === 'desc'
      ? `b.${spec.metric} - a.${spec.metric} || (${dim.tiebreak})`
      : `a.${spec.metric} - b.${spec.metric} || (${dim.tiebreak})`;

  return `/**
 * GENERATED by scripts/stages/codegen.mjs — do not edit by hand.
 * Report: ${spec.title}
 * Dimension: ${spec.dimension} · Metric: ${spec.metric} · Order: ${spec.direction}
 */
import type {
  Report,
  ReportDefinition,
  ReportRow,
  Rollup,
  ${dim.rowType},
} from '../../lib/types';

const ID = ${JSON.stringify(spec.id)};
const TITLE = ${JSON.stringify(spec.title)};
const LIMIT = ${spec.limit};

/**
 * The narrow projection this report needs. Written as a \`Pick\` so that
 * removing a column from ${dim.rowType} breaks this module at compile time
 * instead of silently producing a chart of \`undefined\`.
 */
type Source = Pick<${dim.rowType}, ${JSON.stringify(dim.label)} | ${JSON.stringify(spec.metric)}>;

function project(rows: readonly ${dim.rowType}[]): Source[] {
  return rows.map((row) => ({ ${dim.label}: row.${dim.label}, ${spec.metric}: row.${spec.metric} }));
}

function toReportRows(items: readonly Source[], total: number): ReportRow[] {
  const out: ReportRow[] = [];
  for (const item of items) {
    out.push({
      key: ${dim.keyExpr},
      value: item.${spec.metric},
      share: total === 0 ? 0 : item.${spec.metric} / total,
    });
  }
  return out;
}

export const report: ReportDefinition<${JSON.stringify(spec.dimension)}> = {
  id: ID,
  title: TITLE,
  dimension: ${JSON.stringify(spec.dimension)},
  metric: ${JSON.stringify(spec.metric)},
  unit: ${JSON.stringify(spec.unit)},
  limit: LIMIT,
  compute(rollup: Rollup): Report {
    const source = project(rollup.${dim.source});
    const total = source.reduce((sum, item) => sum + item.${spec.metric}, 0);
    const ordered = source.slice().sort((a, b) => ${comparator});
    return {
      id: ID,
      title: TITLE,
      dimension: ${JSON.stringify(spec.dimension)},
      metric: ${JSON.stringify(spec.metric)},
      unit: ${JSON.stringify(spec.unit)},
      rows: toReportRows(ordered.slice(0, LIMIT), total),
      total,
    };
  },
};

export default report;
`;
}

function registrySource(plan) {
  const imports = plan
    .map((spec, i) => `import { report as report${i} } from './reports/${spec.id}';`)
    .join('\n');
  const entries = plan.map((_, i) => `  report${i},`).join('\n');
  return `/**
 * GENERATED by scripts/stages/codegen.mjs — do not edit by hand.
 * ${plan.length} report modules.
 */
import type { AnyReport } from '../lib/types';

${imports}

export const registry: readonly AnyReport[] = [
${entries}
];

export const reportIds: readonly string[] = registry.map((report) => report.id);
`;
}

export async function runCodegen(config) {
  // Cleared rather than merged: a module left over from a larger previous run
  // would still be imported by nothing but would still be type-checked, which
  // is the kind of thing that makes a build mysteriously slow.
  await rm(REPORTS_DIR, { recursive: true, force: true });
  await mkdir(REPORTS_DIR, { recursive: true });

  const plan = planModules(config.modules);
  line(`planning ${num(plan.length)} report modules across ${COMBOS.length} dimension/metric pairs`);

  let bytes = 0;
  const writes = [];
  for (const spec of plan) {
    const source = moduleSource(spec);
    bytes += Buffer.byteLength(source);
    writes.push(writeFile(join(REPORTS_DIR, spec.file), source, 'utf8'));
    line(`  emit ${spec.file.padEnd(34)} ${String(source.split('\n').length).padStart(3)} lines`);
    // Flushed in batches so a large plan does not open thousands of handles.
    if (writes.length >= 32) {
      await Promise.all(writes.splice(0, writes.length));
      progress('written', plan.indexOf(spec) + 1, plan.length);
    }
  }
  await Promise.all(writes);

  const registry = registrySource(plan);
  await writeFile(join(GENERATED, 'registry.ts'), registry, 'utf8');
  bytes += Buffer.byteLength(registry);
  line(`  emit ${'registry.ts'.padEnd(34)} ${String(registry.split('\n').length).padStart(3)} lines`);

  return { modules: plan.length, bytes, plan };
}
